version: "3.9"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./db-data:/var/lib/mysql
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env/mysql.env
    ports:
      - "13306:3306"
    cap_add:
      - SYS_NICE
    restart: always

  app:
    build:
      context: .
    volumes:
      - .:/app
    env_file:
      - .env/local.env
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"

