// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Article struct {
	ID        string  `json:"id"`
	User      *User   `json:"user"`
	Title     *string `json:"title"`
	Body      string  `json:"body"`
	CreatedAt string  `json:"createdAt"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
